### ISSUE TITLE
Update to Xcode 6 - Beta 6

### ISSUE THREAD

**Issue by beltex** [MagerValp/MVPCStruct#1]
There's been some syntax changes (among other things) to Swift since this was first written. In particular regarding array declarations and for loop ranges. I made the updates but I'm having issues building the project (may or may not be related to beta 4), otherwise I'd send a PR.
- https://developer.apple.com/swift/blog/?id=3

**Comment by beltex** [comment]
Make that beta 5, just came out today.

**Comment by csann** [comment]
I have downloaded the project and modified it. It now builds and passes all unit tests in Xcode 6.4. I am not very knowledgeable about git. What do I need to do to post my changes for review?

**Comment by beltex** [comment]
Hi @csann!

> I have downloaded the project and modified it. It now builds and passes all unit tests in Xcode 6.4.

Nice!

> I am not very knowledgeable about git. What do I need to do to post my changes for review?

You need to fork this repository, commit your changes, push them up, and then submit a pull request. Here's a [guide from GitHub on that](https://help.github.com/articles/using-pull-requests/). For general background information on Git, see [here](https://git-scm.com/book/en/v2).

Hope that helps!
